### ISSUE TITLE
event.words returning undefined

### ISSUE THREAD

**Issue by danielgolden** [johndatserakis/vue-countable#1]
Hey, man. Super excited about the prospect of this component. Thanks for releasing it!

I'm a bit confused by the docs. Not sure where how to retrieve the output of my counts. I was expecting event.words to return a number of words, but it's returning `undefined`. Here's what I have in my app.vue:

```html
<vue-countable
  :text="notes[selectedNoteIndexInList].contents"
  :elementId="toString(notes[selectedNoteIndexInList].id)"
  @change="change"
>sup yo</vue-countable>
```

...skipping stuff...

```js
import VueCountable from 'vue-countable'
// skipping more irrelevant stuff

export default {
    components: {
      VueCountable
    }
}
```
and then in my methods...
```js
change: function () {
  console.log(event.words)
}
```

`console.log(event)` returns a big object called `MessageEvent` that contains no count data (to my knowledge). And `console.log(event.words)` returns `undefined`.

**Comment by johndatserakis** [comment]
Hey bud - sorry you're having trouble.

In looking at your code I see something which may be a problem - you're not passing the `event` parameter in the actual function initialization. You have this (according to what you wrote):

```javascript
change: function () {
  console.log(event.words)
}
```

You gotta make sure to pass the parameter - or else `event` will be undefined:

```javascript
change: function (event) {
  console.log(event.words)
}
```

Let me know if that fixes your issue. I have a working example here:

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y031q8q7rj)

**Comment by danielgolden** [comment]
hahah, wow yeah that would help, wouldn't it? 

I wish I would've noticed that before because it would've saved me the work of going through and calculating the counts myself the manual way. Unfortunately, I've already done that and don't need the component anymore. Thanks for the quick reply, John. Hopefully, I'll find occasion to revisit this component and save myself some time by using it the future.
