### ISSUE TITLE
[question] Compatibility with Quill/vue-quill-editor

### ISSUE THREAD

**Issue by kieron** [johndatserakis/vue-countable#8]
Hey, how would you make this work with an editor like Quill, or specifically https://github.com/surmon-china/vue-quill-editor?

Sorry, that's broad, but I am trying and coming up with nothing.

**Comment by johndatserakis** [comment]
Sorry I just saw this now. With something like that I think it'd be pretty straightforward. First I would try just using the `content` value from `vue-quill-editor` and sticking that in the `text` prop of `vue-countable`. `vue-countable` just watches whatever variable you want and gives back the stats on it.

If that doesn't work, I would try something similar, but use a computed variable to "mock" the `vue-quill-editor` value.

Let me know what you got so far in a codepen or something and we'll figure it out. Sorry for the late response.

**Comment by kieron** [comment]
Thank you @johndatserakis - that did indeed work, although I am having trouble getting paragraphs to work, it always reports just 1 in the event, I am wondering if that's because quill presents an editable div, and uses actual `p` tags in the div etc, so maybe your counter isn't looking for this.

I only wondered as I noticed your demo uses a textarea. No worries though if my editor isn't suitable for use with your package, and thank you for the help so far :)

**Comment by johndatserakis** [comment]
Hey @kieron,

I see - well in that case, I think there's a few things you could try. 

The first thing I would try is make a computed variable using the `content` from `vue-quill-editor`. 

In that computed variable, you could take the initial `content` and iterate through it, perhaps entering your own line break character wherever you see a closing `</p>`, for example. I believe that the library the powers  `vue-countable` looks for newlines to determine "paragraphs". Basically just try and use the computed variable to shape your content as needed.

Also, you can try to turn on the `stripTags` option through `vue-countable`:

```
<vue-countable
    :text="content"
    elementId="myId"
    stripTags
    @change="change"
/>
```

Maybe that will help with the tags.
